M48
; DRILL file {KiCad 7.0.5-0} date 2023 September 03, Sunday 12:09:57
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-03T12:09:57-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X-0.1138Y0.1652
X0.1138Y0.1652
T2
X-0.126Y-0.1575
X0.126Y-0.1575
T0
M30
